//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewWPF.baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyty
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public string Godzina { get; set; }
        public string TypWizyty { get; set; }
    }
}
